#!/usr/bin/python
# script for sending Dust alert from Seviri Dust mask for Abu Dhabi airport.
# sends alert as a mail .
# date:06/03/18

#############################################################################################################################
import sys ; import datetime as dt ; from rasterstats import zonal_stats

#############################################################################################################################

main='/home/mariners/SEVIRI_DUST/' ; scripts=main+'scripts/' ; inp='/home/mariners/MASKS/'
# inp='/home/mariners/SEVIRI_DUST/scripts/shapefiles/MASKS/'
shp_file=scripts+'shapefiles/abudhabi_100km.shp' ; 

date=str(sys.argv[1]) 
#date='201802200630'

fileName=inp+date+'_MASK.tif'

email_id=["fkaragulian@masdar.ac.ae, mtemimi@masdar.ac.ae","vkvalappil@masdar.ac.ae"] 
# email_id=["vkvalappil@masdar.ac.ae"]
# email_id=["fkaragulian@masdar.ac.ae"]

##########################################################################################################################
def sendmail(message,email_list) :
           from smtplib import SMTP ; from smtplib import SMTPException ; 
           from email.mime.multipart import MIMEMultipart ; from email.mime.text import MIMEText      

           _from         =   "fog@masdar.ac.ae" ;
           _to           =   email_list;
           _sub          =   "Dust Alert (WRF CESAM LAB)  "
           _username     =   'fog' ;
           _password     =   'P@ssw0rd2201'
           _smtp         =   "mail.masdar.ac.ae:587" ;
           #_text_subtype = "plain"

           mail=MIMEMultipart()
           mail["Subject"]  =  _sub
           mail["From"]     =  _from
           mail["To"]       =  ','.join(_to)
           #body = MIMEMultipart('alternative')
           #body.attach(MIMEText(_content, _text_subtype ))
           mail.attach(MIMEText(message))
           try:
               smtpObj = SMTP(_smtp)
               #Identify yourself to GMAIL ESMTP server.
               smtpObj.ehlo()
               #Put SMTP connection in TLS mode and call ehlo again.
               smtpObj.starttls()
               smtpObj.ehlo()
               #Login to service
               smtpObj.login(user=_username, password=_password)
               #Send email
               smtpObj.sendmail(_from, _to, mail.as_string())
               #close connection and session.
               smtpObj.quit()
           except SMTPException as error:
               print "Using Gmail : Error: unable to send email :  {err}".format(err=error)   
               try:
                   _from         =   "fog.masdar@gmail.com" ;
                   _to           =   email_list;
                   _sub          =   "TAF (WRF CESAM LAB)  "
                    
                   #_content      =   "WRF TAF DATA"
                   _username     =   'fog.masdar' ;
                   _password     =   'fog@masdar123'
                   _smtp         =   "smtp.gmail.com:587" ;
                   #_text_subtype = "plain"
                   
                   mail=MIMEMultipart()
                   mail["Subject"]  =  _sub
                   mail["From"]     =  _from
                   mail["To"]       =  ','.join(_to)
                   mail.attach(MIMEText(message))
                   smtpObj = SMTP(_smtp)
                   #Identify yourself to GMAIL ESMTP server.
                   smtpObj.ehlo()
                   #Put SMTP connection in TLS mode and call ehlo again.
                   smtpObj.starttls()
                   smtpObj.ehlo()
                   #Login to service
                   smtpObj.login(user=_username, password=_password)
                   #Send email
                   smtpObj.sendmail(_from, _to, mail.as_string())
                   #close connection and session.
                   smtpObj.quit()

               except:
				  print 'error'
				  return "Error";
################################################################################################################################ 
def mail_body(date_ocs,time_ocs) :

    alert_body="""
This email is automatically generated by Masdar's Dust detection and forecast system. 

This warning is to advise that Dust was detected within 100 Km from Abu Dhabi Airport on {} at {} UTC

Further details are available on the portal: https://earth.masdar.ac.ae/air_quality/seviri.php


For comments and/or questions; please contact:

Dr. Marouane Temimi, Ph.D.,
Associate Professor
Masdar Institute of Science and Technology
Email: mtemimi@masdar.ac.ae   """.format(date_ocs,time_ocs)
    return alert_body
    
############################################################################################################################################    

cnt_f=zonal_stats(shp_file,fileName,nodata=0,all_touched=True)[0]['count'] ; print cnt_f

if cnt_f>5 :                          # Use the threshold count                            
       print "Dust detected with in the Buffer Zone"

       dust_flag=1 ; date_stamp=(dt.datetime.strptime(date,'%Y%m%d%H%M')).strftime('%Y-%m-%d') ; 
       time_stamp=(dt.datetime.strptime(date,'%Y%m%d%H%M')).strftime('%H:%M:%S')      
       alert=mail_body(date_stamp,time_stamp)
       sendmail(alert,email_id)   
    
else:
       print "No Dust detected:"     

quit()

